//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace migration
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCInfo_t
    {
        public decimal CCInfoID { get; set; }
        public decimal CustomerID { get; set; }
        public string CCNum { get; set; }
        public string CCExpDate { get; set; }
        public Nullable<decimal> CCTypeID { get; set; }
        public Nullable<byte> IsDefault { get; set; }
        public Nullable<byte> ImportSource { get; set; }
        public Nullable<decimal> ContactID { get; set; }
        public bool Active { get; set; }
    
        public virtual Contact_t Contact_t { get; set; }
    }
}
