//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace migration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact_t
    {
        public Contact_t()
        {
            this.CCInfo_t = new HashSet<CCInfo_t>();
        }
    
        public decimal ContactID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CompanyName { get; set; }
        public string EmailAddress { get; set; }
        public string StreetLine1 { get; set; }
        public string StreetLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
        public string Country { get; set; }
        public Nullable<decimal> PhoneID1 { get; set; }
        public Nullable<decimal> PhoneID2 { get; set; }
        public Nullable<decimal> FaxID { get; set; }
        public Nullable<byte> ImportSource { get; set; }
        public Nullable<byte> Status { get; set; }
    
        public virtual ICollection<CCInfo_t> CCInfo_t { get; set; }
    }
}
