//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace migration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_t
    {
        public Customer_t()
        {
            this.CCInfo_t = new HashSet<CCInfo_t>();
        }
    
        public decimal CustomerID { get; set; }
        public string AR_CustomerID { get; set; }
        public Nullable<decimal> AssociateID { get; set; }
        public Nullable<decimal> ContactID { get; set; }
        public Nullable<decimal> BillingContactID { get; set; }
        public Nullable<decimal> LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<decimal> CustomerStatusID { get; set; }
        public Nullable<byte> ImportSource { get; set; }
        public Nullable<decimal> CustomerTypeID { get; set; }
        public Nullable<short> InvoiceDistributionTypeID { get; set; }
        public Nullable<System.DateTime> CreatedDatetime { get; set; }
        public string AdditionalRecipient1 { get; set; }
        public string AdditionalRecipient2 { get; set; }
        public Nullable<bool> TaxExempt { get; set; }
        public string TaxComment { get; set; }
    
        public virtual ICollection<CCInfo_t> CCInfo_t { get; set; }
        public virtual Contact_t Contact_t { get; set; }
        public virtual Contact_t Contact_t1 { get; set; }
    }
}
