//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace migration
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LARSEntities : DbContext
    {
        public LARSEntities()
            : base("name=LARSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CCInfo_t> CCInfo_t { get; set; }
        public DbSet<Contact_t> Contact_t { get; set; }
        public DbSet<Customer_t> Customer_t { get; set; }
    }
}
